---
- name: Prepare Mock Server
  hosts: mock_server
  become: true
  tasks:
    - name: Start mock server
      raw: "nohup java -Dfile.encoding=UTF-8 -cp /mockserver-netty-jar-with-dependencies.jar:/libs/* -Dmockserver.propertyFile=/mockserver.properties org.mockserver.cli.Main -serverPort 1080 </dev/null >/dev/null 2>&1 & sleep 1"
      changed_when: false

- name: Set Expectations
  hosts: mock_server
  connection: local
  gather_facts: false
  tasks:
    - name: Reset mock server expectations
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/reset"
        method: PUT
        status_code: 200
        headers:
          Content-Type: application/json
        validate_certs: false

    - name: Create api PUT expectation for api definition import role
      uri:
        url: "https://{{ inventory_hostname }}:1080/mockserver/expectation"
        method: PUT
        body:
          httpRequest:
            method: "PUT"
            path: "/api/v1/services/api-definitions/f1-api/versions/v1/import"
          httpResponse:
            statusCode: 202
            body:
              currentStatus:
                state:
                  selfConfigState:
                    configured: 0
                    configuring: 1
                    deleting: 0
                    error: 0
                    isConfigured: false
                    isConfiguring: true
                    isDeleting: false
                    isError: false
                    total: 1
        status_code: 201
        body_format: json
        headers:
          Content-Type: application/json
        validate_certs: false
